### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by tgomesfork** [cchamplin/atom-debug-ui#2]
[Enter steps to reproduce:]

1. Open a .conf file
2. Right click inside .conf file

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: [atom-debug-ui](https://github.com/cchamplin/atom-debug-ui) package 1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /home/tgomes/.atom/packages/atom-debug-ui/lib/servicesregistry.js:92

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at ServicesRegistry.locateServicesForScope (/packages/atom-debug-ui/lib/servicesregistry.js:92:30)
    at ServicesRegistry.locateServicesForEditor (/packages/atom-debug-ui/lib/servicesregistry.js:82:17)
    at AtomDebugUI.shouldDisplayMenuInScope (/packages/atom-debug-ui/lib/debug-ui.js:141:42)
    at Object.shouldDisplay (/packages/atom-debug-ui/lib/debug-ui.js:26:23)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/opt/atom/resources/app/src/context-menu-manager.js:181:25)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/opt/atom/resources/app/src/context-menu-manager.js:102:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/atom/resources/app/src/context-menu-manager.js:203:33)
    at WindowEventHandler.handleDocumentContextmenu (/opt/atom/resources/app/src/window-event-handler.js:257:44)
```

### Commands

```
     -1:26.1.0 core:confirm (input.hidden-input)
     -1:26.1.0 git-plus:stash-pop (input.hidden-input)
     -1:17.8.0 intentions:highlight (input.hidden-input)
     -1:17.8.0 core:save (input.hidden-input)
     -0:34.1.0 intentions:highlight (input.hidden-input)
     -0:33.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:33.4.0 core:paste (input.hidden-input)
     -0:29.8.0 core:confirm (input.hidden-input)
     -0:23.5.0 editor:consolidate-selections (input.hidden-input)
     -0:23.5.0 core:cancel (input.hidden-input)
     -0:23.2.0 editor:consolidate-selections (input.hidden-input)
     -0:23.2.0 core:cancel (input.hidden-input)
     -0:21.9.0 editor:consolidate-selections (input.hidden-input)
     -0:21.9.0 core:cancel (input.hidden-input)
     -0:18.6.0 intentions:highlight (input.hidden-input)
     -0:18.2.0 pane:reopen-closed-item (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-debug-ui 1.0.1 
atom-ide-ui 0.11.1 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-show-project-name 0.1.4 
atom-ternjs 0.18.3 
autocomplete-java 1.2.7 
autocomplete-modules 2.0.0 
autocomplete-xml 0.9.4 
behat-atom 0.1.2 
bliss-syntax 0.3.3 
bliss-ui 0.6.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
docblockr 0.13.7 
dracula-syntax 2.0.6 
dracula-ui 0.6.0 
duotone-dark-syntax 2.1.0 
emmet 2.4.3 
file-icons 2.1.19 
firacode 0.3.0 
git-plus 7.10.2 
highlight-selected 0.13.1 
html-head-snippets 0.2.0 
html-id-class-snippets 1.4.1 
hyperclick 0.0.0 
ide-java 0.8.3 
ide-json 0.2.1 
ide-php 0.7.14 
intentions 1.1.5 
jquery-snippets 11.0.0 
js-hyperclick 1.13.0 
lcov-info 0.12.0 
less-than-slash 0.18.0 
line-diff-details 1.9.0 
linter 2.2.0 
linter-javac 1.9.4 
linter-jshint 3.1.6 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-twig 0.4.2 
linter-ui-default 1.7.1 
lipsum 0.1.0 
local-history 4.3.1 
minimap 4.29.8 
minimap-autohider 1.5.4 
nucleus-dark-ui 0.12.3 
open-in-browser 0.5.2 
php-cs-fixer 4.1.1 
php-debug 0.3.0 
php-getters-setters 0.5.5 
php-twig 4.0.0 
phpunit 1.2.0 
project-manager 3.3.5 
script 3.17.3 
seti-syntax 1.1.3 
seti-ui 1.10.0 
split-diff 1.5.2 
spotify-linux 0.3.2 
styri-syntax 0.2.0 
Sublime-Style-Column-Selection 1.7.4 
teletype 0.13.2 
text-pastry 0.6.1 
theme-switch 0.6.0 
vaporwave-syntax 0.0.6 
vaporwave-ui 0.0.2 
xatom-debug-nodejs 0.9.3 
xml-formatter 0.11.0 
```

**Comment by cchamplin** [comment]
I haven't been able to reproduce this but it's possible it might be fixed in v1.0.4 which just landed. Can you update and let me know?

**Comment by NNeto** [comment]
It happened to me right after disabling the package and right clicking before restarting Atom.

**Comment by oddvalue** [comment]
[Enter steps to reproduce:]

1. Right click in file

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-debug-ui](https://github.com/cchamplin/atom-debug-ui) package 1.0.4


### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /Users/mutley/.atom/packages/atom-debug-ui/lib/servicesregistry.js:93

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at ServicesRegistry.locateServicesForScope (/packages/atom-debug-ui/lib/servicesregistry.js:93:30)
    at ServicesRegistry.locateServicesForEditor (/packages/atom-debug-ui/lib/servicesregistry.js:83:17)
    at AtomDebugUI.shouldDisplayMenuInScope (/packages/atom-debug-ui/lib/debug-ui.js:141:42)
    at Object.shouldDisplay (/packages/atom-debug-ui/lib/debug-ui.js:26:23)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:181:25)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:102:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:203:33)
    at WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:257:44)
```

### Commands

```
     -4:48.1.0 core:move-left (input.hidden-input)
  5x -4:47.8.0 find-and-replace:select-next (input.hidden-input)
     -4:46.1.0 core:move-left (input.hidden-input)
     -4:32.1.0 docblockr:parse-enter (input.hidden-input)
     -4:32.1.0 editor:newline (input.hidden-input)
undefined -4:16.6.0 core:undo (input.hidden-input)
undefined -4:11.1.0 core:redo (input.hidden-input)
     -4:02.7.0 docblockr:parse-enter (input.hidden-input)
     -4:02.7.0 editor:newline (input.hidden-input)
     -4:02.4.0 docblockr:parse-enter (input.hidden-input)
     -4:02.4.0 editor:newline (input.hidden-input)
     -3:58.4.0 core:backspace (input.hidden-input)
     -2:22.9.0 symbols-view:toggle-project-symbols (input.hidden-input)
     -2:19.2.0 core:confirm (input.hidden-input)
  2x -2:04.9.0 core:backspace (input.hidden-input)
     -1:40.9.0 symbols-view:toggle-file-symbols (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.5 
atom-debug-ui 1.0.4 
atom-ide-ui 0.12.0 
busy-signal 1.4.3 
change-case 0.6.5 
craft-twig 0.4.0 
custom-title 1.0.1 
docblockr 0.13.7 
file-icons 2.1.21 
git-diff-details 1.4.0 
highlight-selected 0.13.1 
ide-php 0.7.14 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-markdown 0.25.1 
language-nunjucks 4.2.1 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
minimap-titles 1.15.0 
multiline-tab 0.2.1 
open-files 0.8.2 
php-debug 0.3.5 
php-ide-serenata 4.1.2 
php-twig 4.0.0 
pigments 0.40.2 
project-manager 3.3.6 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
swackets 0.35.0 
tab-title 0.3.5 
terminal-tab 0.5.7 
text-pastry 0.6.1 
todo-show 2.3.0 
```
