### ISSUE TITLE
Failed to load php-debug

### ISSUE THREAD

**Issue by five07** [cchamplin/atom-debug-ui#5]
When activating php-debug or atom-debug-ui, the following error throws. php-debug is not available as a debugger nor does it begin listening on the configured port.

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-debug-ui](https://github.com/cchamplin/atom-debug-ui) package 1.0.4

### Stack Trace

Failed to activate the atom-debug-ui package

```
At Cannot read property 'debug' of undefined

TypeError: Cannot read property 'debug' of undefined
    at ServiceManager.activate (/packages/atom-debug-ui/lib/services.js:66:36)
    at PHPDebug.consumeDebugUI (/packages/php-debug/lib/php-debug.js:232:22)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:397:75)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:30)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/src/config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:1226:62)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:1052:23)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:715:18)
    at Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:905:16)
    at Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:362:31)
```

### Commands

```
     -0:12.7.0 debugger:show-attach-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-blackboard-dark-mod.theme-atom-dark-ui)
     -0:11.3.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-blackboard-dark-mod.theme-atom-dark-ui)
     -0:02.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-debug-ui 1.0.4 
atom-ide-ui 0.12.0 
blackboard-dark-mod 0.2.0 
busy-signal 1.4.3 
ide-php 0.7.14 
ide-typescript 0.7.6 
intentions 1.1.5 
linter 2.0.0 
linter-phpcs 1.6.8 
linter-ui-default 1.7.1 
php-debug 0.3.5 
remote-sync 4.1.8 
script 3.17.3 
symbols-tree-view 0.14.0 
```

**Comment by five07** [comment]
Commented out the line of code that throws and restarted. Works as expected.
